name: asi
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=21.2.4
  - python=3.9.7
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.37.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==1.0.0
    - alembic==1.7.5
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - async-generator==1.10
    - attrs==21.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - black==22.1.0
    - bleach==4.1.0
    - certipy==0.1.3
    - cffi==1.15.0
    - charset-normalizer==2.0.11
    - click==8.0.3
    - cryptography==36.0.1
    - cycler==0.11.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.3
    - executing==0.8.2
    - flatbuffers==2.0
    - fonttools==4.29.1
    - greenlet==1.1.2
    - idna==3.3
    - ipykernel==6.7.0
    - ipython==8.0.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - isort==5.10.1
    - jax==0.2.27
    - jaxlib==0.1.76
    - jedi==0.18.1
    - jinja2==3.0.3
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.1
    - jupyter-server==1.13.4
    - jupyter-telemetry==0.1.0
    - jupyterhub==2.1.1
    - jupyterlab==3.2.8
    - jupyterlab-code-formatter==1.4.10
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.2
    - mako==1.1.6
    - markupsafe==2.0.1
    - matplotlib==3.2.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbclassic==0.3.5
    - nbclient==0.5.10
    - nbconvert==6.4.1
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - notebook==6.4.8
    - numpy==1.22.1
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pamela==1.0.0
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.0
    - platformdirs==2.4.1
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.26
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.11.2
    - pyopenssl==22.0.0
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.2
    - pytz==2021.3
    - pyzmq==22.3.0
    - requests==2.27.1
    - ruamel-yaml==0.17.20
    - ruamel-yaml-clib==0.2.6
    - scipy==1.7.3
    - seaborn==0.11.2
    - send2trash==1.8.0
    - six==1.16.0
    - sniffio==1.2.0
    - sqlalchemy==1.4.31
    - stack-data==0.1.4
    - terminado==0.13.1
    - testpath==0.5.0
    - tomli==2.0.0
    - tornado==6.1
    - traitlets==5.1.1
    - tqdm==4.63.0
    - typing-extensions==4.0.1
    - urllib3==1.26.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - widgetsnbextension==3.5.2
